// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWpksjQpAcAgsAHOyqNocIYjqJl5_8Nzc',
    appId: '1:1010242652120:web:e0949bd0fc4445420c94ad',
    messagingSenderId: '1010242652120',
    projectId: 'sabell-app',
    authDomain: 'sabell-app.firebaseapp.com',
    storageBucket: 'sabell-app.firebasestorage.app',
    measurementId: 'G-0Y6XXMN25G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySmJnh14nl_41Bgtacy6GsXRDPSStGoY',
    appId: '1:1010242652120:android:e5b0bd238bd15eac0c94ad',
    messagingSenderId: '1010242652120',
    projectId: 'sabell-app',
    storageBucket: 'sabell-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxfX_vdH62dv7gaVKea3h5ldmwYecaWA0',
    appId: '1:1010242652120:ios:831016b277d20c8e0c94ad',
    messagingSenderId: '1010242652120',
    projectId: 'sabell-app',
    storageBucket: 'sabell-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterSabel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxfX_vdH62dv7gaVKea3h5ldmwYecaWA0',
    appId: '1:1010242652120:ios:831016b277d20c8e0c94ad',
    messagingSenderId: '1010242652120',
    projectId: 'sabell-app',
    storageBucket: 'sabell-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterSabel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWpksjQpAcAgsAHOyqNocIYjqJl5_8Nzc',
    appId: '1:1010242652120:web:bac8d66938f82b200c94ad',
    messagingSenderId: '1010242652120',
    projectId: 'sabell-app',
    authDomain: 'sabell-app.firebaseapp.com',
    storageBucket: 'sabell-app.firebasestorage.app',
    measurementId: 'G-6ZJZSL71CB',
  );
}
